### ISSUE TITLE
How to run with uhyve on M1? 

### ISSUE THREAD

**Issue by playXE** [hermit-os/hermit-rs#267]
When trying to run with uhyve I get this error for both aarch64 and x86_64 targets:
```
➜  rusty-hermit git:(master) ✗ uhyve target/aarch64-unknown-hermit/debug/hello_world 
thread 'main' panicked at 'Unable to create VM! Is the hypervisor interface (e.g. KVM) activated?: Error', src/bin/uhyve.rs:326:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
➜  rusty-hermit git:(master) ✗ uhyve target/x86_64-unknown-hermit/debug/hello_world
thread 'main' panicked at 'Unable to create VM! Is the hypervisor interface (e.g. KVM) activated?: Error', src/bin/uhyve.rs:326:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I followed all installation instructions from README.md. uhyve is built from source

**Comment by stlankes** [comment]
Do you use the version from crates.io or from out GitHub repo?

**Comment by playXE** [comment]
> Do you use the version from crates.io or from out GitHub repo?

From GH repo

**Comment by playXE** [comment]
@stlankes I get the following error when installing from crates.io:
```
error[E0433]: failed to resolve: could not find `arch` in `self`
  --> /Users/pk/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-9.1.1/src/lib.rs:64:37
   |
64 |         let result = unsafe { self::arch::__cpuid_count(a, c) };
   |                                     ^^^^ could not find `arch` in `self`

   Compiling heck v0.3.3
For more information about this error, try `rustc --explain E0433`.
error: could not compile `raw-cpuid` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `uhyve v0.0.28`, intermediate artifacts can be found at `/var/folders/h8/r749nn_x13g41tfjzbqyx7gm0000gn/T/cargo-installiOBHpK`

```

**Comment by jounathaen** [comment]
I think this issue is outdated now. Uhyve has some rudimentary (but untested) support for macos + aarch64. If the issue persists, it'd be great if it could be reopened in the [uhyve repo](https://github.com/hermit-os/uhyve).
